name: dragon-build
description: Build a package with dragon

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
    branches:
      - master
      - 'dev/**'

inputs:
  add_rootless:
    description: 'Do you want the build to be rootless, default false.'
    required: false
    default: 'no'

runs:
  using: "composite"
  steps:
    - run: |
        python3 -m pip install --upgrade pip
        pip3 install --break-system-packages dragon
      shell: bash
    - run: |
        dragon
      shell: bash
    - run: |
        if [ "${{ inputs.add_rootless }}" = "yes" ]; then
          dragon c b r rootless
        else
          dragon c b r
        fi
      shell: bash
